### ISSUE TITLE
What is the format of input?

### ISSUE THREAD

**Issue by guangtu5** [LeeDoYup/RobustSTL#10]
@LeeDoYup 
Dear Doyup Lee,

I am a starter with Robust STL. How can I import my own data from Excel? What is the format of input? 

Kind regards,
Jason

**Comment by LeeDoYup** [comment]
The code and example is based on generated sample.
When you use your own data, see the jupyter notebook file and replace the generated sample.

You can load your data according to your data format.
(if you load data from excel, refer pandas.read_excel )
