### ISSUE TITLE
 Certificate of primal infeasibility found.

### ISSUE THREAD

**Issue by jnuvenus** [LeeDoYup/RobustSTL#2]
hello，
    I have try to use RobustSTL() function to decompose a time series,  but return error: 

    return sol['x'][:n]
TypeError: 'NoneType' object is not subscriptable.

Then I found that this error  got from  "sol = solvers.conelp(c, Fi, h, dims, kktsolver = Fkkt,  
        primalstart={'x': x0, 's': s0}, dualstart={'z': z0})"  which return the error "Certificate of primal infeasibility found.".
If there is any method to solve this problem？ I am looking forward to hearing from you, thanks.

**Comment by jnuvenus** [comment]
I found that This erroe was caused by the wrong selection of  reg1, reg2. But got other errrors.
How select the parameters : reg1, reg2,  dn1, dn2, ds1, ds2 ?

**Comment by LeeDoYup** [comment]
The hyper-parameters are not trainable and we have to decide manually.
They are related with bilateral filter and regularization parameters.
