### ISSUE TITLE
Trend seems to depend on the first value of sample

### ISSUE THREAD

**Issue by junhyk** [LeeDoYup/RobustSTL#6]
Hi,
I've tried to test your great code with other samples.
And I found the trend is always highly dependent on the first value of the samples
![image](https://user-images.githubusercontent.com/26551254/64140339-0db8ff00-ce3f-11e9-9c84-02425ce2d8bb.png)
Note that since my sample is non-seasonal I manually set `seasons_tilda` as zeros
Do you have any idea?

Thanks

**Comment by LeeDoYup** [comment]
I think it has a local optimal problem in solving trend extraction.
Have you tried normalization (to set the mean value of series as "0") ?

**Comment by LeeDoYup** [comment]
and it is true that 
RobustSTL can highly depends on the first value.
(because it sequentially sovle the convex optimization problem.)

**Comment by junhyk** [comment]
I guess normalization works a bit.
![image](https://user-images.githubusercontent.com/26551254/64154053-04de2280-ce6b-11e9-92bf-c9c80e367b48.png)
Thanks for your insight :)

**Comment by LeeDoYup** [comment]
Thank you for using my codes.
For you information (in my experience), 
RobustSTL algorithm suffer when abnormal patterns are many or repeated in same season (in here, when abnormal patterns occurs consecutively).

**Comment by LeeDoYup** [comment]
In addition, i think your data contain lots of peak values and no seasonality.
Then, just smoothing + 3 sigma can be effective way to detect outliers.
